### ISSUE TITLE
Q2: Identify full user journey tracking for purchasing a digital record

### ISSUE THREAD

**Issue by piriyapordes** [nationalarchives/tna-google-tag-manager-scripts#18]
- [x] Draw out full user journey
- [x] Identify points of interaction and data to be captured
- [x] Break down data to metatags and GTM data objects
- [x] Document user journey, Javascript, GTM code, testing

**Comment by piriyapordes** [comment]
Acceptance criteria:

- digital downloads only

- offsite user is paying for something

**Comment by hoake** [comment]
Has the documentation be done for this?
