### ISSUE TITLE
Q2: Implement tracking code for full user journey tracking for purchasing any digital item (receipt page)

### ISSUE THREAD

**Issue by piriyapordes** [nationalarchives/tna-google-tag-manager-scripts#19]
- [x] Next collect `<meta>` tag info from Receipt page
- [x] Make sure data is available for every step of the user journey: Product view, shopping basket, meta tags
- [x] Documentation: describe the GTM script in Github README, describe how you see the data should be coming through and confirmation of the exact data coming through to GA, how you physically test the script as a developer

**Definition of done:** Push and Test data

**Comment by piriyapordes** [comment]
unsure about first task
