### ISSUE TITLE
Q3: FE Image viewer keystroke tracking for the image viewer functions (thumbnails, zoom, expand etc.)

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#28]
## Push image viewer functions to the DataLayer
Each function will need to have it's own event and the dataLayer will need to cleared before the next event happens
```
"event": "Discovery image viewer",
"eventCategory": "Discovery",
"eventAction": "Image viewer functions",
"eventLabel": "NAME_OF_THE_LABEL_FUNCTION" //e.g. zoom in, pan left
```
For the thumbnails:
```
"event": "Discovery image viewer",
"eventCategory": "Discovery",
"eventAction": "Image viewer functions",
"eventLabel": "Thumbnail page 1" //The number will change to represent each thumbnail clicked
```

I'm adding a list of the functions for testing purposes
- [x] View first image
- [x] View previous image
- [x] Zoom in
- [x] Zoom out
- [x] Pan left
- [x] Pan right
- [x] Pan up
- [x] Pan down
- [x] Reset
- [x] Enter full screen mode
- [x] Exit full screen mode
- [x] Print
- [x] View next image
- [x] View last image
- [x] Click on thumbnail or thumbnail page 2, 3 log thumbnail clicks

**Comment by hoake** [comment]
Script to be deployed to Discovery environment for testing
