### ISSUE TITLE
FE dev Ecommerce tracking for shopping basket step 1 -3

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#30]
## View basket page 
(similar to the receipt page, note there is no transaction ID here)
- [x] When a user views the basket the following needs to be push to the dataLayer 
- [x] INSERT CHECKOUT PROPERTY UNDER ECOMMERCE ONE AND PRODUCTS UNDER THE CHECKOUT PROPERTY
- [x] DO NOT PUSH PURCHASE OBJECT TO DATALAYER
[https://developers.google.com/tag-manager/enhanced-ecommerce#checkoutstep](url)
```
 "event": "checkout",
 "ecommerce": {
    "checkout": {           //Note the change compared to the receipt page
         "actionField": {
            "step": 1  },          //Note the step change
         "products": [{
            "name": "WO 398",
            "price": "3.50",
            "brand": "The National Archives",
            "category": "Digital Record",
            "variant": "WO 398/188/1",
            "quantity": 1
       //List all other product objects
      }]
}
```
- [x] Removing items from the basket - This will be client side with a click on a button. THIS IS GREAT DON'T CHANGE
```
dataLayer.push({
  "event": "removeFromCart",
  "ecommerce": {
    "currencyCode": "GBP",
    "remove": {
      "products": [{
        "name": "WO 398",
        "price": "3.50",
        "brand": "The National Archives",
        "category": "Digital Record",
        "variant": "WO 398/188/14",
        "quantity": 1
      }]
    }
  }
});
```
## Summary page
- [x] When a user views their order summary the following needs to be pushed to the dataLayer
- [x] INSERT CHECKOUT PROPERTY UNDER ECOMMERCE ONE AND PRODUCTS UNDER THE CHECKOUT PROPERTY
- [x] DO NOT PUSH PURCHASE OBJECT TO DATALAYER
```
dataLayer.push({
  "event": "checkout",
  "ecommerce": {
      "checkout": {
         "actionField": {
            "step": 2},
         "products": [{
       //Repeat product listing
}
```
- [x] On submit order button
```
 "event": "transaction",
  "ecommerce": {
     "checkout": {                  
         "actionField": {
            "step": 3},
         "products": [{
        //Repeat product listing
```
## On receipt page
- [x] REMOVE CHECKOUT_OPTION
- [x] ADD step 4 to purchase actionField
```
dataLayer.push({
'event': 'checkoutOption',
  'ecommerce': {
'checkout_option': {                  //Remove checkout_option
        'actionField': {'step': step 4, 'option': Receipt}   //<meta name="WT.si_p" content="Step 4"> 
    'purchase': {
      'actionField': {
        'step': 4,
        'id': '657715845504212R',                              // Transaction ID. Required for purchases and refunds.
        'affiliation': 'Discovery Store',    //<meta name="WT.si_n" content="Discovery store">
        'revenue': '7.00',                     // <meta name="WT.tx_total" content="7.00"> Total transaction value 
        'tax':'0.00',                              
        'shipping': '0.00',                    //We'll need to check it it applies for record copying
        },
      'products': [{                            // List of productFieldObjects.
        'name': 'WO 398',

**Comment by hoake** [comment]
We need to check this has been peer reviewed and then push to test.

**Comment by hoake** [comment]
Script to be deployed to Discovery environment for testing
