### ISSUE TITLE
Tracking for subject filter in Discovery

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#44]
## Script development for
- [x] Discovery
- [ ] Wordpress
- [ ] Custom html in GTM

## Dependencies
- [x] Yes
[https://github.com/nationalarchives/tna-google-tag-manager-scripts/issues/46](url)
- [ ] No

#### Event tracking
- [x] capture the labels for subject filter and push to dataLayer when Refine button is submitted.
-  event:Discovery
-  eventCategory: Discovery
-  eventAction: TYPE_OF_FILTER_APPLIED
-  eventLabel: NAME_OF_FILTER_LABEL_CHECKED (comma delimited)

## Acceptance/test criteria
 *examples of output in GA debug*
**Ensure the custom html tag has been created and published**
- [x] hitType (&t) event
- [x] eventCategory (&ec) Discovery
- [x] eventAction (&ea) Subject filters applied
- [x] eventLabel (&el) Census, Conflict,

**Comment by hoake** [comment]
Hi James, 
THe script is working well on test environment. My only comment is the eventLabel is displaying the filter id  instead of the text of the filter. E.g. 
```
<label for="C10092">   // this is what the eventLabel is currently showing
              Army    //this is what it should be displaying
<span>(1)</span>
</label>```

**Comment by hoake** [comment]
![screenshot 2019-01-30 at 13 33 47](https://user-images.githubusercontent.com/14073889/51984633-bd865280-2493-11e9-9880-422584afb418.png)
![screenshot 2019-01-30 at 13 34 43](https://user-images.githubusercontent.com/14073889/51984710-e1e22f00-2493-11e9-953b-95f86aed7551.png)
This is all good and can go live
