### ISSUE TITLE
Meta tag for filtered search in Discovery

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#45]
## Dependencies
- [ ] Yes
- *add or link to any dependencies*
- [x] No

## Tasks that effect specific pages
On /results/r page when a user has filtered a basic search
- [x] Without any filters 
```
<meta name="WT.cg_n" content="Search results" />
```
- [x] Basic search with date only filter
```html
<meta name="DCSext.filtertype" content="Date filter" />
<meta name="WT.cg_n" content="Date filtered search" />
```
- [x]  Held by TNA 
```html
<meta name="WT.cg_n" content="Refine search held by TNA" />
```
- [x]  Held by TNA, filtered by collection, subject etc.
```html
<meta name="WT.cg_n" content="TNA search filters applied" />
<meta name="DCSext.filtertype" content="NAME_OF_FILTER_APPLIED" />  coma delimited if more than one filter type applied
```
- [x]  Held by Other Archives 
```html
<meta name="WT.cg_n" content="Refine search held by other Archives" />
```
- [x]  Other archives filters
```html
<meta name="WT.cg_n" content="Other archives search filters applied" />
<meta name="DCSext.filtertype" content="NAME_OF_FILTER_APPLIED" /> coma delimited if more than one filter type applied
```
- [x] Remove DCSext.searchtype meta tag

No changes to Record Creators and advanced search meta tags

## Acceptance/test criteria to be checked on TEST environment
*Examples of meta tag content criteria*
**Basic search with date only filter**
- [ ] meta name="DCSext.filtertype" content="Date filter"
- [ ] meta name="WT.cg_n" content="Filtered basic search"
 
**Held by TNA** 
- [ ] meta name="WT.cg_n" content="Refine search held by TNA"

 **TNA filters** 
- [ ] meta name="WT.cg_n" content="TNA search filters applied"
- [ ] meta name="DCSext.filtertype" content="Date, subject, Collection"  

**Held by Other Archives** 
- [ ] meta name="WT.cg_n" content="Refine search held by other Archives"

**Other archives filters**
- [ ] meta name="WT.cg_n" content="Other archives search filters applied"
- [ ] meta name="DCSext.filtertype" content="Held by, Date"

[Search page analysis.xlsx](https://github.com/nationalarchives/tna-google-tag-manager-scripts/files/2676342/Search.page.analysis.xlsx)
