### ISSUE TITLE
BE: Discovery bookmark tracking 

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#51]
Create meta tags to collect content group meta tag from 'my account'

- [ ]On https://secure.nationalarchives.gov.uk/Login/youraccount
```
<meta name="WT.cg_n" content="Your account" />
```
- [ ] http://discovery.nationalarchives.gov.uk/account/bookmarks
```
<meta name="WT.cg_n" content="My account - Bookmark" />
```
- [ ] http://discovery.nationalarchives.gov.uk/account/tags
```
<meta name="WT.cg_n" content="My account - Tags" />
```
- [ ] http://discovery.nationalarchives.gov.uk/account/yourorders
```
<meta name="WT.cg_n" content="My account - Orders" />
```
