### ISSUE TITLE
BE dev: Meta tags for Discovery account tracking

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#52]
## Dependencies
- [ ] Yes
- *add or link to any dependencies*
- [x] No

## Tasks that effect specific pages
On the account pages (any page on and below /account/ and if customdimension3='signed-in' change ContentGroup value from 'meta tag not available' to '**Customer account**'

## Acceptance/test criteria
- *The follow needs to be available in the DataLayer*
**ContentGroup: "Customer account"**
customDimension1: "Meta tag not available"
customDimension2: "not subscribed"
customDimension3: "signed-in"

On the following pages:

- [ ] http://discovery.nationalarchives.gov.uk/account/bookmarks

- [ ] http://discovery.nationalarchives.gov.uk/account/tags

- [ ] http://discovery.nationalarchives.gov.uk/account/yourorders

**Comment by hoake** [comment]
James can you add this to the Discovery repository
