### ISSUE TITLE
FE: Tracking for bookmark sorting

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#59]
## Script development for
- [x] Discovery
- [ ] Wordpress
- [ ] Custom html in GTM

## Dependencies/linked to task on another board
- [x] Yes
- *https://github.com/nationalarchives/Subscription-Offering/issues/163*
- [ ] No

#### Event tracking
- [x] WHEN a user is signed in on http://discovery.nationalarchives.gov.uk/account/bookmarks and sorts bookmarks with one of the dropdown options THEN send the selected option to the dataLayer as:
event: "Discovery" 
eventAction: "Bookmark sorting"
 eventCategory:"Discovery"
 eventLabel:"{SELECTED_OPTION_VALUE}"

## Acceptance/test criteria
- *Examples of output in GA debug/dataLayer*
- [x] hitType: event *(GA debug)*
- [x] eventAction: "Bookmark sorting"
- [x] eventCategory: "Discovery"
- [x] eventLabel: "Created latest"
