### ISSUE TITLE
Q1: Make it easy to access the collection

### ISSUE THREAD

**Issue by MariangF** [nationalarchives/tna-google-tag-manager-scripts#6]
To answer questions and find gaps as defined for our sub offer test group

## Tasks BE Dev
- [x] Create tag with subscriber and the subscription name.
Example

```
<meta name=""DCSext.subscription"" content=""subscriber-1A OR not subscribed"">
<meta name=""DCSext.registered"" content""registered OR not regsitered"">
<meta name=""DCSext.signedin"" content=""signed-in OR not signed-in"">"
```
- [x] Add GTM tag to /sign-in/ pages
- [x] Set TFS and access to subscription application for james
- [x] Access to sign-in (secure.nationalarchives single sign-on, reader registration) for developers

## Task FE Dev
- [x] Create script to collect meta tag values for Subscriber, catalogue refence and discovery account sign in

GTM DL output:
customDimension1=VALUE_OF_DCSext.docref_META_TAG
customDimension2=VALUE_OF_DCSext.subscription_META_TAG
customDinemsion3=VALUE_OF_DCSext.signedin_META_TAG

## Tasks PO
In GTM 
- [x] Create 3 custom variables DLV - customDimension(1-3)
- [x] Add custom dimensions to all global settings
In GA
- [x] Add Custom dimension in property settings keeping the index number consistent with dimension number and set scope 1=hit, 2=user, 3=session.

**Comment by MariangF** [comment]
Tasks FE Dev
Create <meta> tag with subscriber and the subscription name.
Example
<meta name="DCSext.subscriber" content="subscriber-1A">

Tasks BE Dev- Add GTM tag to /sign-in/ pages
Tasks BE dev - Set TFS and access to subscription application for james
Access to sign-in (secure.nationalarchives single sign-on, reader registration) for developers

Tasks PO - Add GA config

Task FE Dev- Create script to collect meta tag values for Subscriber and catalogue refence
GTM DL output: 
customDimension1=VALUE_OF_DCSext.subscriber_META_TAG 
customDimension2=VALUE_OF_DCSext.docref_META_TAG

**Comment by hoake** [comment]
Meta tag for
```
<meta name="DCSext.registered" content="registered OR not regsitered" />
```
not created because of difficulties assigning registered token.

**Comment by hoake** [comment]
These tasks have been done and are in test.
