### ISSUE TITLE
Collecting meta tag values for other archives data

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#73]
## Script development for
- [x] Discovery
- [ ] Wordpress
- [ ] Custom html in GTM

## Dependencies
- [x] Yes
- https://github.com/nationalarchives/tna-google-tag-manager-scripts/issues/41
- https://github.com/nationalarchives/manage-your-collections/issues/8
- [ ] No

#### Custom dimension tracking

- [ ] When the meta tag name is one of the following send its value to the dataLayer as a custom dimension.

Meta tag name | Example Meta tag values | DataLayer parameter | DataLayer examples
-- | -- | -- | --
DCSext.colltype | A2A | customDimension5 | customDimension5: "A2A"
DCSext.dsource | Manor | customDimension5 | customDimension5: "Manor"
DCSext.place | National Library of Wales | customDimension6 | customDimension6: "National Library of Wales"
DCSext.repository | Dudley Archives and Local History Service | customDimension6 | customDimension6: "Dudley Archives and Local History Service"
DCSext.rdata | GB/NNAF/M272225 | customDimension7 | customDimension7: "GB/NNAF/M272225"
DCSext.reposlocate | British repository | customDimension8 | customDimension8: "British repository"
Meta tag not available | empty | Do not send to the dataLayer | empty

## Acceptance/test criteria
- *examples of output in GA debug or DataLayer*
- [ ] customDimension5: "A2A"
- [ ] customDimension6: "National Library of Wales: Department of Collection Services"
- [ ] customDimension7: "D\PC\oake/1"
- [ ] customDimension8: "British repository"
