### ISSUE TITLE
FE dev: Tracking for Discovery search UI

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#75]
## Script development for
- [x] Discovery
- [ ] Wordpress
- [ ] Custom html in GTM

## Dependencies
- [ ] Yes
- *add or link to any dependencies*
- [x] No

#### Event tracking
**On successful search submit (no errors) push the following to the DataLayer:**
- [x] event: "Discovery search"
- [x] eventCategory: "Discovery homepage search"
- [x] eventAction: "Search submitted"
- [x] eventLabel: [search-all-collections:yes or no > start-date:yes or no > end-date:yes or no > held-by: All records(Default) or get changed value ] //

**When there is an error on search submit push the following to the DataLayer:**
- [x] event: "Discovery search"
- [x] eventCategory: "Discovery homepage search"
- [x] eventAction: "Search errors"
- [x] eventLabel: [field id: error message > field id: error message]

## Acceptance/test criteria
- *Example output in GA debug or DataLayer*

**Successful search**
- [x] event: "Discovery search"
- [x] eventAction: Search submitted
- [x] eventCategory: Discovery homepage search
- [x] eventLabel: search-all-collections:yes or no > start-date:yes or no > end-date:yes or no > held-by:All collections OR The National Archives only OR Other Archives only

**Unsuccessful search**
- [x] event: "Discovery search"
- [x] eventAction: Discovery homepage search
- [x] eventCategory: Search errors
- [x] eventLabel: search-all-collections: Please enter keyword or catalogue reference > start-date: Please enter 4 digits

**Comment by hoake** [comment]
Hey @netdesignr Do you know if this tracking for SearchUI is still in place now that it has been redeveloped. If it hasn't we'll need to think about how we can implement it.

**Comment by hoake** [comment]
Re-writing script to work with server side UI
