### ISSUE TITLE
FE dev: Tracking for WTEG feedback

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#76]
## Script development for
- [x] Discovery
- [ ] Wordpress
- [ ] Custom html in GTM

## Dependencies
- [ ] Yes
- *add or link to any dependencies*
- [x] No

#### Event tracking
- [x] event: "DiscoveryWTEGfeedBack"
- [x] eventCategory: "Discovery what to expect feedback"
- [x] eventAction: "Did you find this helpful: [Yes or No]"
- [x] eventLabel: "Comments: [comment entered in text box OR No comment made]"

## Acceptance/test criteria
*All events should have the following in GA debug*
- [x] hitType: event
- [x] eventCategory:

If user clicks YES and did not leave a comment
- [x] eventAction: Did you find this helpful: **Yes**
- [x] eventLabel: Comments: **comment entered in text box**

If user clicks YES and did leave a comment
- [x] eventAction: Did you find this helpful: **Yes**
- [x] eventLabel: Comments: **No comment made**

If user clicks NO and did not leave a comment
- [x] eventAction: Did you find this helpful: **No**
- [x] eventLabel: Comments: **No comment made**

If user clicks NO and did leave a comment
- [x] eventAction: Did you find this helpful: **No**
- [x] eventLabel: Comments: **comment entered in text box**
