### ISSUE TITLE
FE dev: Tracking for promo events for What to expect guide

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#78]
## Script development for
- [x] Discovery
- [ ] Wordpress
- [ ] Custom html in GTM

## Dependencies
- [x] Yes
- *add or link to any dependencies*
- [ ] No

#### Ecommerce tracking
When there is a Discovery details page with
```<meta name="Dcsext.wteg " content="What to expect guide" />```
Push the following to the dataLayer
- [x] EC **Promo view** event - 
```
"ecommerce": {                 //THIS IS THE BIT I FORGOT TO PUT IN
"promoView": {
      "promotions": [{
        "id": "wteg",
        "name": "What to expect guide",
        "creative": "Expanding link",
        "position": "Below catalogue description"
      }]
    }
}                                          //AND THIS
```
When WTEG button is clicked 
- [x] EC **Promo click** event - 
```
"event": "promotionClick",
  "ecommerce": {
    "promoClick": {
      "promotions": [{
        "id": "wteg",
        "name": "What to expect guide",
        "creative": "Expanding button",
        "position": "Below catalogue description"
      }]
    }
  }
```
### Promo click on watermarked image viewer
When then is a details page with
```<meta name="DCSext.imgviewer" content="Image Viewer Watermarked">```
And expanding link is clicked
```<a href="#imageViewerLink" id="imageViewerLink" class="imageViewerExpander">Preview an image of this record.</a>```

Push the following Promo click to the dataLayer (a promo view check and object has already been created)
```
"event": "promotionClick",
  "ecommerce": {
    "promoClick": {
      "promotions": [{
        "id": "ivp",
        "name": "Image Viewer Watermarked",
        "creative": "Image viewer",
        "position": "Below record description"
      }]
    }
  }
```

### What to expect guide pages (WO 95)
In the dataLayer:
- [x] On page load:
```
ecommerce:
promoView: //Double check this
promotions: Array(1)
0: {id: "wteg", name: "What to expect guide", creative: "Expanding button", position: "Below catalogue description"}
```
- [x] When WTEG button is clicked
```
ecommerce:
promoClick: //Double check this
promotions: Array(1)
0: {id: "wteg", name: "What to expect guide", creative: "Expanding button", position: "Below catalogue description"}
```
### Details pages with image viewer marked
- [x] On page load
```
ecommerce:
promoClick: //Double check this
promotions: Array(1)
0: {id: "ivp", name: "Image Viewer Watermarked", creative: "Image viewer", position: "Below record description"}
```
## TEST criteria for TEST environment
In GA debug:
### What to expect guide pages (WO 95)
- [x] hitType: event
- [x] ec:promo "1" creative (&promo1cr) **Expanding button**
- [x] ec:promo "1" id       (&promo1id) **wteg**
- [x] ec:promo "1" name     (&promo1nm) **What to expect guide**
- [x] ec:promo "1" position (&promo1ps) **Below catalogue description**
- [x] ec:promo action       (&promoa)   **view**
### Click on What to expect guide button
- [x] hitType: event
- [x] ec:promo "1" creative (&promo1cr) **Expanding button**
- [x] ec:promo "1" id       (&promo1id) **wteg**
- [x] ec:promo "1" name     (&promo1nm) **What to expect guide**
- [x] ec:promo "1" position (&promo1ps) **Below catalogue description**
- [x] ec:promo action       (&promoa)   **click**
### Details pages with image viewer marked
- [x] hitType: event
- [x] ec:promo "1" creative (&promo1cr) **Image viewer**
- [x] ec:promo "1" id       (&promo1id) **ivp**
- [x] ec:promo "1" name     (&promo1nm) **Image Viewer Watermarked**
- [x] ec:promo "1" position (&promo1ps) **Below record description**
- [x] ec:promo action       (&promoa)   **click**

**Comment by hoake** [comment]
Sorry it's so long. Let me know if you would like it split up

**Comment by hoake** [comment]
Hey James, I'm so sorry but I've missed a very small but very important part of the PromoView snippett. The snippett should be wrapped in ```"ecommerce": {}```. Apart from my mistake it's in the dataLayer as expected but doesn't get picked up by GTM. I've amended the script above (it's the first one)

**Comment by hoake** [comment]
It's working great on test, thanks so much @JamesWChan and @punalsc
