### ISSUE TITLE
FE dev: Tracking for WTEG image modal

### ISSUE THREAD

**Issue by hoake** [nationalarchives/tna-google-tag-manager-scripts#79]
## Script development for
- [x] Discovery
- [ ] Wordpress
- [ ] Custom html in GTM

## Dependencies
- [ ] Yes
- *add or link to any dependencies*
- [x] No

#### Event tracking 
- [x] when a user closes, esc or clicks/touches away from the modal window
event: "Popup"
eventCategory: "What to expect guide popup image"
eventAction: "Close window" OR "Esc key pressed" OR "Clicked outside window"

>To be added in another sprint
eventLabel: "Document series e.g. ADM 188 from 
```<meta name="DCSext.docref" content="ADM 188/758/55839">```

### Test criteria for dataLayer and GA debug

- [x] When a user clicks X to close the window
```
event: "Popup"
eventCategory: "What to expect guide popup image"
eventAction: "Close window"
```
- [x] When a user uses Esc key to close the window
```
event: "Popup"
eventCategory: "What to expect guide popup image"
eventAction: "Esc key pressed"
```
- [x] When a user clicks away from the window to close it
```
event: "Popup"
eventCategory: "What to expect guide popup image"
eventAction: "Clicked outside window"
```
